// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Torito.Data.Persistance.Context;

namespace Torito.Data.Migrations
{
    [DbContext(typeof(ToritoContext))]
    [Migration("20201208101121_Initial_migration")]
    partial class Initial_migration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Torito.Data.Persistance.DataModels.AnnotationDbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("End")
                        .HasColumnType("int");

                    b.Property<int?>("EntityDboId")
                        .HasColumnType("int");

                    b.Property<string>("NormalizedText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Probability")
                        .HasColumnType("float");

                    b.Property<int?>("Start")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EntityDboId");

                    b.ToTable("Annotations");
                });

            modelBuilder.Entity("Torito.Data.Persistance.DataModels.EntityDbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.HasKey("Id");

                    b.ToTable("Entities");
                });

            modelBuilder.Entity("Torito.Data.Persistance.DataModels.HashtagDbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("End")
                        .HasColumnType("int");

                    b.Property<int?>("EntityDboId")
                        .HasColumnType("int");

                    b.Property<int?>("Start")
                        .HasColumnType("int");

                    b.Property<string>("Tag")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EntityDboId");

                    b.ToTable("Hastags");
                });

            modelBuilder.Entity("Torito.Data.Persistance.DataModels.TweetDbo", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

                    b.Property<string>("AuthorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EntitiesId")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2020, 12, 8, 4, 11, 21, 561, DateTimeKind.Local).AddTicks(47));

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2020, 12, 8, 4, 11, 21, 553, DateTimeKind.Local).AddTicks(1157));

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EntitiesId");

                    b.ToTable("Tweets");
                });

            modelBuilder.Entity("Torito.Data.Persistance.DataModels.AnnotationDbo", b =>
                {
                    b.HasOne("Torito.Data.Persistance.DataModels.EntityDbo", null)
                        .WithMany("Annotations")
                        .HasForeignKey("EntityDboId");
                });

            modelBuilder.Entity("Torito.Data.Persistance.DataModels.HashtagDbo", b =>
                {
                    b.HasOne("Torito.Data.Persistance.DataModels.EntityDbo", null)
                        .WithMany("Hashtags")
                        .HasForeignKey("EntityDboId");
                });

            modelBuilder.Entity("Torito.Data.Persistance.DataModels.TweetDbo", b =>
                {
                    b.HasOne("Torito.Data.Persistance.DataModels.EntityDbo", "Entities")
                        .WithMany()
                        .HasForeignKey("EntitiesId");

                    b.Navigation("Entities");
                });

            modelBuilder.Entity("Torito.Data.Persistance.DataModels.EntityDbo", b =>
                {
                    b.Navigation("Annotations");

                    b.Navigation("Hashtags");
                });
#pragma warning restore 612, 618
        }
    }
}
